### ISSUE TITLE
Wrong id used for teacher filter

### ISSUE THREAD

**Issue by mwehr** [moodleuulm/moodle-block_course_overview_campus#10]
Hi,

I think there is a small issue in the teacher filter part.
On line 439 the only id field which is requested is ra.id which is the roleid. 
The correct id I think should be the user id which would be:
 $courseteachers = get_role_users($teacherroles, $context, true, 'ra.id, u.id, u.lastname, u.firstname, r.sortorder', 'u.lastname, u.firstname');

can you confirm that?

regards,

Mario

**Comment by abias** [comment]
Hi Mario,

I added the fields to the get_role_users() function call for 2.8 compatibility. In our installation, the teacher filter works with this code without debug messages and other errors.

Could you please describe why u.id should be added..? Does the filter fail in your installation or do you see performance problems with the current code?

Thanks,
Alex

**Comment by mwehr** [comment]
Hi Alex,

The teacher filter works without failing. Sometimes the generated list shows multiple entries of the same name.
I become aware of this because one of my collegues asked me why his name was listed multiple times in the teacher filter. What I've seen so far is that the multiple listing of the same name occurs because of ra.id is later used for the user.id at line 452 
ra.id changes per context and it looks like that for every course where the user has a teacher role we get a new ra.id -> user.id which results in a new list entry in the teacher filter. 

regards,

Mario

**Comment by abias** [comment]
Hi Mario,

now I see what's the problem. I could reproduce the bug and added the column to the function call as you proposed in commit 1cfbee7a0e111fd8dbdb8f5927037b4e4257772c.

Thanks for reporting,
Alex

**Comment by mwehr** [comment]
Perfect!
,... and thx for the credits :-)
Mario
