### ISSUE TITLE
Eye icon not work

### ISSUE THREAD

**Issue by gogrichard** [moodleuulm/moodle-block_course_overview_campus#11]
Hi everyone!

I have the following problem in my moodles. (2.5.9 with Clean theme, 2.8.5+ with Decaf theme)

When i try to use the "eye" icon the courses doesn't get hidden. The icon changes, but the course still remain visible(in couse settings too).

So:
![1](https://cloud.githubusercontent.com/assets/12169778/7390711/1368baec-ee7b-11e4-84a3-9a9c5e9beb5e.JPG)

Now i click on the eye icon:

![2](https://cloud.githubusercontent.com/assets/12169778/7390708/1367063e-ee7b-11e4-9d7b-79a5b661d1b7.JPG)

Click on the "Managing hidden courses".

![3](https://cloud.githubusercontent.com/assets/12169778/7390709/13673c3a-ee7b-11e4-8f2a-87235a6278fb.JPG)

Click on the eye icons:

![4](https://cloud.githubusercontent.com/assets/12169778/7390710/1368776c-ee7b-11e4-8bfd-0b34c76d2cf9.JPG)

As you can see, no effect on the course's setting.

**Comment by abias** [comment]
Hi Richard,

as far as I see, this is a usability issue and no bug.

The eye icon in the block has (from the very beginning) only hidden the course in the course list for the current user, but it does neither affect the course list of other users nor does it change the course's visibility setting.

On the MoodleMoot 2014, I was already told that the behaviour of the eye icon can be misunderstood by some users. In the aftermath, I thought about replacing the icon with some other icon (which does not use the eye metaphor), but I didn't find a better icon. So I added a global setting to the block to disable the course-hiding functionality completely for admins who have to deal with users misunderstanding the eye icon.

If you have a proposal for another icon, I would be very grateful to take your advice.

Thanks,
Alex
