### ISSUE TITLE
Missing course category attribute

### ISSUE THREAD

**Issue by alendit** [moodleuulm/moodle-block_course_overview_campus#13]
Hi,

we've noticed, that if you set the setting `categorycoursefilter` to `false`, but `secondrowshowcategoryname` to `true` you get an error `Notice: Undefined property: stdClass::$categoryname in ...`.

The reason is that the `categoryname` property is set, only if the option `categorycoursefilter` [is enabled](https://github.com/moodleuulm/moodle-block_course_overview_campus/blob/master/block_course_overview_campus.php#L412-L418).

As far as I can tell, it's enough to change the [line 412](https://github.com/moodleuulm/moodle-block_course_overview_campus/blob/master/block_course_overview_campus.php#L412) to

    if ($coc_config->categorycoursefilter === true || $coc_config->secondrowshowcategoryname === true) {

but you may consider a more general solution. 

I can submit a pull request, of course ;)

**Comment by abias** [comment]
Hi Dimitri,

thanks for pointing me to this issue.

Your proposed fix does not solve the problem completely, but I think I solved the problem and will push a commit soon.

Thanks,
Alex
