### ISSUE TITLE
Suggestion: Students see list of all courses they are enrolled to, but can only access those available.

### ISSUE THREAD

**Issue by csch1** [moodleuulm/moodle-block_course_overview_campus#15]
Hi, I had raised this suggestion in moodle.org wrt the default Course Overview block, but we are now immersed in using Course Overview on Campus. Well done for developing such an amazing block.

**Situation**
At the start of every academic year, we receive a number of queries from students who claim that cannot see some of their courses listed in the block, the likelihood being that the teacher had not yet made the course visible to students (rather than the students were not enrolled to their course).

**Suggestion**
We feel that it would be beneficial for all parties if the course overview block could also show all courses which a student is enrolled to, in spite of whether the course is set as visible or not. Obviously, courses not set as visible would remain inaccessible. Such feature would make the system more 'transparent', in the sense that students would know which courses they are enrolled to, and that its simply the teacher who has not yet made a course accessible to them.

Any chance of including this feature or some guidance to tweak the current block?

Thanks!

**Comment by abias** [comment]
Hi Chris,

thanks for your feedback and sorry for the late reply.

I completely understand your use case and I find it quite interesting. We encounter the same issues when our lecture term starts.

Implementing your suggestion would lead us another step away from the way block_course_overview from Moodle core handles course lists, but that's life :)

Now, how can we implement that?
Currently, the block uses the Moodle core function enrol_get_my_courses() to fetch the list of courses I am enrolled in. This function already drops courses if they are not visible and if I don't have the moodle/course:viewhiddencourses capability in the course context (like, especially, a teacher has). Thus, the block never gets to see the inaccessible courses you would like to add to the course list.

We could propose to add a new parameter to enrol_get_my_courses() in Moodle core to let us fetch courses which are invisible and inaccessible, but I don't know if that proposal would be successful.

As a quick solution (which could be done in parallel to proposing the solution in Moodle core), we could just copy enrol_get_my_courses() over to the block's lib, enhance it there and call our own fork of the function.

Afterwards, we would have to visually distinguish in the block's course list between accessible and inaccessible courses.

And finally, we would have to decide if we just link to an inaccessible course as we do to an accessible course and rely on the error message Moodle core presents to the user (something like "This course is currently not available") or if we don't link to an inaccessible course and present our own notification about the inaccessibility of the course within the block's course list.

One more thing: If we enhance the course list this way, we can also add a notification for the teachers to an invisible course in the course list telling them that they currently can see the course but students can't.


Now here's the question:
Do you have time and development experience to implement this feature and submit a pull request?

Thanks,
Alex

**Comment by abias** [comment]
Hi, 

this issue has been stale for 2 years now. 

While we still support the spirit of this issue, it won't be implemented anymore as we are foreseeably transitioning our own usage of this block to the Dashboard blocks which have been dramatically improved from Moodle 3.6 on and thus can't spend any more resources on improving this plugin substantially.

Cheers,
Alex
