### ISSUE TITLE
Bug: Refreshing VLE page shows category as empty

### ISSUE THREAD

**Issue by Naomi-Mifsud** [moodleuulm/moodle-block_course_overview_campus#16]
Hi,

Thanks for this block. We are currently testing the latest version of the Course Overview on Campus block on Moodle 3.1.

We have noticed that if a user chooses a specific category and accesses a course within the category, then clicks the 'Back' button, the category is displayed as empty. This also happens if the user clicks the 'Refresh' button.

Moreover, we've noticed that if a user chooses a top-category with several parent categories, and accesses a course within the category, upon clicking the 'Back' button, only those courses which fall directly within the top-category are displayed. To resolve this, the user has to choose another category, and then go back to the required category to display all necessary courses.

We've also tested this with debug mode on, and the following was displayed:
**Notice:** Undefined variable: hidemanagebox in **/var/www/html/vle/blocks/course_overview_campus/block_course_overview_campus.php** on line **1293**

While this is not a major issue, and we can work around it, we appreciate if there's a fix for this in the future.

Much thanks in advance,
Naomi

**Comment by Naomi-Mifsud** [comment]
Hi,

Kindly note that further to my initial message, we have continued with further testing and noticed that upon refreshing the page or going back, only the areas which are directly within the top-category are displayed. Therefore if the top-category does not contain any areas, but the sub-categories within it contain areas, then upon refreshing, nothing is displayed, which might confuse our users.

Can you please provide us with some insight with respect to this issue.

Thanks,
Naomi

**Comment by dfeatherstone** [comment]
Hi,

We have found the same issue which, as our system is setup with a top level category containing a number of sub-categories below which are the courses, means that whenever a user opens this block they see no courses until they move to another category and back, is a big problem.

What we have also noticed is that the system administrators do not see the problem but everybody else does!

Hope that this can be sorted out soon.

Denis

**Comment by abias** [comment]
Hi all, 

sorry for my slow reply. We are very busy with preparing Moodle for our next lecture term, but this shouldn't be your problem.

I will try to look into this problem as soon as possible and will come back to you with a solution.

Thanks,
Alex

**Comment by abias** [comment]
Hi @Naomi-Mifsud, hi @dfeatherstone, 

thanks for your patience. Daily work has kept me busy until now, but I was finally able to work on this ticket.

This ticket contains three separate issues:
* The problem that the top level category filter did not show lower-level courses on first page load is clearly a bug and I am very sorry that this has sneaked in. Please find the patch on https://github.com/moodleuulm/moodle-block_course_overview_campus/commit/70cd2fa1bc42b258ac03c3be287c892c34aa9dce or wait some more days until we publish the 3.2 version of the block which will contain this fix.
* The problem that the course list does not match the filter values after using the browser's back functionality is also an apparent bug, but I don't know if we really can do anything about it. Another developer of us is currently having a deeper look into this problem.
* The "Undefined variable: hidemanagebox" PHP notice was a third, separate problem and did not have anything to do with the problems above. Additionally, it did not cause any problems in production. Please find the patch on https://github.com/moodleuulm/moodle-block_course_overview_campus/commit/54a59fb91b7337a5eee7940e6f53efd9c3a0dd20 or wait some more days until we publish the 3.2 version of the block which will contain this fix.

Thanks,
Alex

**Comment by Naomi-Mifsud** [comment]
Hi Alex,

Thank you for your work on this.

We will wait until version 3.2 is published.

Thanks,
Naomi

**Comment by abias** [comment]
Hi Naomi,

FYI: The 3.2 version was just published on https://moodle.org/plugins/block_course_overview_campus.

Thanks,
Alex

**Comment by Naomi-Mifsud** [comment]
Hi Alex,

Thanks again for the update.

We will be installing and testing it soon, and will keep you updated.

Thanks,
Naomi

**Comment by abias** [comment]
Hi Naomi,

concerning the problem that the course list does not match the filter values after using the browser's back functionality, the v3.2-r2 version which was just published on https://moodle.org/plugins/block_course_overview_campus contains the fix you were looking for.

Thanks,
Alex

**Comment by Naomi-Mifsud** [comment]
Hi Alex,

Thanks once again and apologies for re-opening this issue.

We have recently tried to install the latest version which contains the fix, v3.2-r2, however, since we have Moodle 3.1 installed we were unable to update to the latest version.

Given that Moodle 3.1 is a long term support release, we will not be updating to Moodle 3.2 in the near future. Are there any possibilities of having the fix for Moodle 3.1 please?

Thanks,
Naomi

**Comment by abias** [comment]
Hi Naomi,

I understand your request, but I would like to point you to our Release support policy on https://github.com/moodleuulm/moodle-block_course_overview_campus/blob/master/README.md#moodle-release-support. We normally don't publish updates for older Moodle versions, even if Moodle 3.1 is LTS, due to limited resources.

I referenced the patches for your problems above, you could try to patch your latest 3.1 version yourself.

Or you could get the latest 3.2 version, remove the line $plugin->requires = ... from version.php and run this version on 3.1 on your own risk. This version should also work on 3.1, but you might get an suboptimal filter layout as we have switched the filter layout to Bootstrap 4 for theme_boost.

Sorry...
Alex

**Comment by Naomi-Mifsud** [comment]
Hi Alex,

Thank you for your prompt reply.

We'll look into the possibilities you have kindly recommended.

Thanks again,
Naomi

**Comment by Naomi-Mifsud** [comment]
Hi Alex,

Just want to let you know that we have used the patches and patched the latest 3.1 version, and it was successful.

Thanks,
Naomi

**Comment by abias** [comment]
Hi Naomi,

great to hear that you could use the patches!

Thanks,
Alex
