### ISSUE TITLE
Plugin Name in language file

### ISSUE THREAD

**Issue by 2shediac** [moodleuulm/moodle-block_course_overview_campus#25]
For the version - 2017063000, running on a linux box, the pluginname on the block title is not translating properly.

Can you let us know if there is any updates available?

Thanks

**Comment by abias** [comment]
Hi Derek,

I am fully aware that we are late with updating this plugin, but it is not dead yet.

Apart from this basic lag, could you please elaborate what you mean with "the pluginname on the block title is not translating properly"?

Thanks,
Alex

**Comment by 2shediac** [comment]
![m33courseoverview](https://user-images.githubusercontent.com/16323254/33737797-5fd19992-db65-11e7-84e6-afd20f167c85.png)

Hi Alex - I think your plugin is in great shape - except for this minor issue. I have attached a screen shot. Its Moodle 3.3 - cache has been cleared etc.

Let me know if you need anything else..

**Comment by abias** [comment]
Hi Derek,

thank you for the screenshot. The added some clarification. However, I am confused how this can happen.

As you see, in https://github.com/moodleuulm/moodle-block_course_overview_campus/blob/master/lang/en/block_course_overview_campus.php#L67, there is a language pack entry for "pluginname".

On https://github.com/moodleuulm/moodle-block_course_overview_campus/blob/master/block_course_overview_campus.php#L52, the title of the block is set defined. It is set to a setting of the block which defaults back to the "pluginname" string as you can see on https://github.com/moodleuulm/moodle-block_course_overview_campus/blob/master/settings.php#L105.

So, if you installed the plugin correctly, the block should have a valid title.

Could you please re-install the block and check if this changes anything? Additionally, please turn on debugging to see if there are any debug messages added to the page when the block is shown.

Thanks,
Alex

**Comment by 2shediac** [comment]
Hi Alex - I think I found the problem. Its the settings when you install the plugin. There is a title that you can setup. See the attached screen shot
![setting](https://user-images.githubusercontent.com/16323254/33830777-8c9c481a-de43-11e7-9c11-d42dbdb18628.png)

Thats where the issue is (I think)

**Comment by abias** [comment]
Hi Derek,

sorry for the late reply.

Well, your screenshot is about theme_altitude and not about block_course_overview_campus. I simply don't understand what's the problem and what I should fix.

Again, could you please re-install the block and check if this changes anything? Additionally, please turn on debugging to see if there are any debug messages added to the page when the block is shown.

Thanks,
Alex

**Comment by 2shediac** [comment]
![courseoverview](https://user-images.githubusercontent.com/16323254/35223541-b5e27b18-ff4f-11e7-8f22-0f0735755fb4.png)

Hi - if you look at this revised screenshot - the block title is: [[pluginname]] on the settings screen. So the title in the block is being drawn from this screen, which while correct is confusing. It looks to our customers / etc that its a missing language entry. If you could change the default to not use double brackets and perhaps put the name in, that would help reduce the confusion.

Thanks
