### ISSUE TITLE
User can see hidden categories

### ISSUE THREAD

**Issue by dfeatherstone** [moodleuulm/moodle-block_course_overview_campus#27]
When a category is hidden non-admin users cannot see it or the sub-categories and courses within it.  However in our dashboard which uses this block they are still visible.
We are using Moodle 3.3.5+ and course_overview_campus v3.3-r1.

Yours Denis Featherstone
Hertford Regional College

**Comment by abias** [comment]
Hi Denis,

so you mean that users who are enrolled in a visible course which is located in a hidden course category can access this course with block_course_overview_campus? Well, this is a standard behaviour of Moodle and I don't think that block_course_overview_campus behaves different than other areas of Moodle. A hidden category does not mean "courses in this category are not accessible", it just means something like "the category is hidden in the category tree when you browse the courses on /course/index.php".

(Visible) courses in hidden categories are still accessible for enrolled users or users who know the URL of the course. You can even find visible courses in hidden categories in the Moodle course search (see https://tracker.moodle.org/browse/MDL-52810).

We can argue if this behaviour of Moodle core is a bug or a feature. But I don't see yet what block_course_overview_campus would be doing wrong here...

Thanks,
Alex
