### ISSUE TITLE
"No courses" text

### ISSUE THREAD

**Issue by baileyn1** [moodleuulm/moodle-block_course_overview_campus#33]
Hi. This plugin would benefit with some "No courses to display" text, if there werent any. Maybe toggleable in the settings.

**Comment by abias** [comment]
Hi, 

thank you for your suggestion.

Currently, the block shows "Currently, you are not enrolled in any courses" if you are really not enrolled in any courses which is true especially for users who log into Moodle for the first time.
However, you are right, the block does not show any note if you have selected some filter combination which will give you an empty list of courses.

While we still support the spirit of this issue, it won't be done anymore as we are foreseeably transitioning our own usage of this block to the Dashboard blocks which have been dramatically improved from Moodle 3.6 on and thus can't spend any more substantial resources on this plugin.

Cheers,
Alex
