### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by alekiy** [moodleuulm/moodle-block_course_overview_campus#5]
Hey,

we are dealing with great performance problems. Users with more then 20 courses have to wait sometimes over 30 secounds until the site with the block attached to it gets loaded. Please take a look at the existing moodle issue for the course overview block: https://tracker.moodle.org/browse/MDL-34785

Thx Alex

**Comment by zozoh94** [comment]
Hello @abias,
I have the same problem with Moodle 3.5.9 and your plugin in version v3.5-r2 (2018092600).
Can the enablecoursenews value still be a problem ?
I didn't touch MAX_MODINFO_CACHE_SIZE value.
